### ISSUE TITLE
Launch Site Button Failing to Launch Site

### ISSUE THREAD

**Issue by m1j09830** [cisagov/domain-manager-ui#136]
# 🐛 Summary #

The launch site button located under both the Demo and Hosted Zone tabs fails to launch the template that has been selected for the domain.

## To reproduce ##

1. Select domain you want to work with
2. Then select the Template tab
3. Select "Select from templates"
4. Select desired template
5. Ensure all fields are populated 
6. Select "Create Domain HTML"
7. Go to HostedZone tab
8. Add the appropriate NS records to name cheap
9. Ensure records have been propogated
10. Select Options > Launch Site located in Hosted Zone tab

## Expected behavior ##

The site should successfully launch at this point which would be reflected as having a check mark under the "Is Live" column under the Domains tab on the left hand side of the screen.

**Comment by zenine07** [comment]
@m1j09830 I'm going to check that out in the staging environment. When you launch site, it launches through CloudFront and can take up to 10 minutes to launch. After clicking launch, do you see the "Launching in Progress" set to True on the Domain page?

**Comment by zenine07** [comment]
@m1j09830 We found the error and have a fix for it coming in this PR - https://github.com/cisagov/domain-manager-api/pull/237. We are hoping to have the fix in production in the next couple hours. We will post here when it is fixed and that domain can be launched. Thanks for catching this bug so quick and posting an issue!

**Comment by zenine07** [comment]
@m1j09830 The issue has been deployed to the production environment and tested successfully. I'm going to close this issue for now, but feel free to reopen if you have further issues.

**Comment by m1j09830** [comment]
Thank you for the quick turn around on this. I'll reach out if I notice any more errors.
